import { Router } from "express";
import { asyncHandler } from "../../../../utils/asyncHandler.js";
import { authenticate } from "../../middlewares/authMiddleware.js";
import {
  loginRateLimit,
  otpSendRateLimit,
  otpVerifyRateLimit,
  paymentOrderRateLimit,
} from "../../middlewares/rateLimitMiddleware.js";
import {
  addDriverEmergencyContact,
  completeOnboarding,
  createOwnerBusService,
  cancelOwnerBusBookingSeats,
  createDriverPaymentQr,
  handleDriverRazorpayWalletTopupCallback,
  createDriverWithdrawalRequest,
  completePoolingOnboardingRequest,
  createOwnerFleetDriver,
  createOwnerPoolingVehicle,
  updateOwnerFleetDriver,
  updateOwnerPoolingVehicle,
  updateOwnerFleetVehicle,
  deleteCurrentDriverAccount,
  deleteDriverEmergencyContact,
  claimDriverIncentiveReward,
  goOffline,
  goOnline,
  createBusDriverReservation,
  getBusDriverLiveTrip,
  updateBusDriverSchedules,
  startBusDriverLiveTrip,
  updateBusDriverLiveLocation,
  updateBusDriverLiveTripStatus,
  getCurrentDriver,
  getPoolingDriverBookings,
  getBusDriverSeatLayout,
  listBusDriverBookings,
  getDriverPaymentQrStatus,
  getDriverApprovalStatus,
  getDriverDocumentTemplates,
  getDriverVehicleFieldTemplates,
  getDriverEmergencyContacts,
  getDriverIncentives,
  getDriverNotifications,
  deleteDriverNotification,
  clearAllDriverNotifications,
  deleteDriverPrimaryVehicle,
  cancelDriverScheduledRide,
  getDriverScheduledRides,
  listOwnerBusServices,
  getOwnerPoolingVehicles,
  saveDriverFcmToken,
  getOwnerFleetDrivers,
  getOwnerFleetDashboard,
  getOwnerFleetWallet,
  getOwnerFleetZones,
  getOwnerBusBookingCalendar,
  getOwnerBusBookings,
  getMyWallet,
  getOnboardingSession,
  getOnboardingSignupOptions,
  getServiceLocations,
  loginDriver,
  startDriverLoginOtpRequest,
  startPoolingOnboardingRequest,
  saveOnboardingDocuments,
  saveOnboardingRoleDetails,
  saveOnboardingRole,
  saveOnboardingPersonal,
  saveOnboardingReferral,
  saveOnboardingVehicle,
  verifyOnboardingLicenseDocument,
  verifyOnboardingVehicleRc,
  registerDriver,
  requestDriverAccountDeletion,
    startOnboarding,
    createDriverWalletTopupOrder,
    createDriverPhonePeWalletTopupOrder,
  verifyDriverWalletTopup,
  verifyDriverPhonePeWalletTopup,
  verifyCurrentDriverBankDetails,
  verifyCurrentDriverBankDocument,
  verifyCurrentDriverUpiDetails,
  verifyCurrentDriverLicenseDocument,
  verifyCurrentDriverGstinDocument,
  verifyCurrentDriverPanDocument,
  verifyCurrentDriverRcDocument,

  updateCurrentDriver,
  updateDriverVehicle,
  updateOwnerBusService,
  verifyOnboardingOtp,
  verifyDriverLoginOtpRequest,
  verifyPoolingOnboardingOtpRequest,
  addOwnerVehicle,
  deleteOwnerBusService,
  deleteOwnerPoolingVehicle,
  getOwnerFleetVehicles,
  deleteOwnerFleetVehicle,
  updateCurrentDriverDocument,
  getPoolingOnboardingSessionRequest,
  savePoolingOnboardingDetailsRequest,
  uploadPoolingOnboardingImageRequest,
} from "../controllers/driverController.js";
import { triggerDriverSosAlert } from '../../safety/controllers/safetyController.js';

export const driverRouter = Router();

driverRouter.post("/register", asyncHandler(registerDriver));
driverRouter.post("/login", loginRateLimit, asyncHandler(loginDriver));
driverRouter.post("/auth/send-otp", otpSendRateLimit, asyncHandler(startDriverLoginOtpRequest));
driverRouter.post(
  "/auth/verify-otp",
  otpVerifyRateLimit,
  asyncHandler(verifyDriverLoginOtpRequest),
);
driverRouter.post(
  "/pooling/onboarding/send-otp",
  otpSendRateLimit,
  asyncHandler(startPoolingOnboardingRequest),
);
driverRouter.post(
  "/pooling/onboarding/verify-otp",
  otpVerifyRateLimit,
  asyncHandler(verifyPoolingOnboardingOtpRequest),
);
driverRouter.get(
  "/pooling/onboarding/session/:registrationId",
  asyncHandler(getPoolingOnboardingSessionRequest),
);
driverRouter.patch(
  "/pooling/onboarding/details",
  asyncHandler(savePoolingOnboardingDetailsRequest),
);
driverRouter.post(
  "/pooling/onboarding/complete",
  asyncHandler(completePoolingOnboardingRequest),
);
driverRouter.post(
  "/pooling/onboarding/upload-image",
  asyncHandler(uploadPoolingOnboardingImageRequest),
);
driverRouter.get(
  "/me",
  authenticate(["driver", "owner", "pooling_driver", "bus_driver"], { allowPending: true }),
  asyncHandler(getCurrentDriver),
);
driverRouter.get(
  "/pooling/bookings",
  authenticate(["pooling_driver"], { allowPending: true }),
  asyncHandler(getPoolingDriverBookings),
);
driverRouter.patch(
  "/me",
  authenticate(["driver", "owner"]),
  asyncHandler(updateCurrentDriver),
);
driverRouter.post(
  "/me/bank-details/verify",
  authenticate(["driver"]),
  asyncHandler(verifyCurrentDriverBankDetails),
);
driverRouter.post(
  "/me/upi/verify",
  authenticate(["driver"]),
  asyncHandler(verifyCurrentDriverUpiDetails),
);
driverRouter.get(
  "/bus/seats",
  authenticate(["bus_driver"]),
  asyncHandler(getBusDriverSeatLayout),
);
driverRouter.get(
  "/bus/bookings",
  authenticate(["bus_driver"]),
  asyncHandler(listBusDriverBookings),
);
driverRouter.post(
  "/bus/reservations",
  authenticate(["bus_driver"]),
  asyncHandler(createBusDriverReservation),
);
driverRouter.get(
  "/bus/live-trip",
  authenticate(["bus_driver"]),
  asyncHandler(getBusDriverLiveTrip),
);
driverRouter.post(
  "/bus/live-trip/start",
  authenticate(["bus_driver"]),
  asyncHandler(startBusDriverLiveTrip),
);
driverRouter.patch(
  "/bus/live-trip/location",
  authenticate(["bus_driver"]),
  asyncHandler(updateBusDriverLiveLocation),
);
driverRouter.patch(
  "/bus/live-trip/status",
  authenticate(["bus_driver"]),
  asyncHandler(updateBusDriverLiveTripStatus),
);
driverRouter.patch(
  "/bus/schedules",
  authenticate(["bus_driver"]),
  asyncHandler(updateBusDriverSchedules),
);
driverRouter.delete(
  "/me",
  authenticate(["driver", "owner"]),
  asyncHandler(deleteCurrentDriverAccount),
);
driverRouter.post(
  "/me/delete-request",
  authenticate(["driver"]),
  asyncHandler(requestDriverAccountDeletion),
);
driverRouter.post(
  "/sos",
  authenticate(["driver", "owner"]),
  asyncHandler(triggerDriverSosAlert),
);
driverRouter.get(
  "/emergency-contacts",
  authenticate(["driver"]),
  asyncHandler(getDriverEmergencyContacts),
);
driverRouter.post(
  "/emergency-contacts",
  authenticate(["driver"]),
  asyncHandler(addDriverEmergencyContact),
);
driverRouter.delete(
  "/emergency-contacts/:contactId",
  authenticate(["driver"]),
  asyncHandler(deleteDriverEmergencyContact),
);
driverRouter.patch(
  "/documents/:documentKey",
  authenticate(["driver", "owner"], { allowPending: true }),
  asyncHandler(updateCurrentDriverDocument),
);
driverRouter.post(
  "/documents/:documentKey/verify-license",
  authenticate(["driver"], { allowPending: true }),
  asyncHandler(verifyCurrentDriverLicenseDocument),
);
driverRouter.post(
  "/documents/:documentKey/verify-pan",
  authenticate(["driver"], { allowPending: true }),
  asyncHandler(verifyCurrentDriverPanDocument),
);
driverRouter.post(
  "/documents/:documentKey/verify-gst",
  authenticate(["driver"], { allowPending: true }),
  asyncHandler(verifyCurrentDriverGstinDocument),
);
driverRouter.post(
  "/documents/:documentKey/verify-rc",
  authenticate(["driver"], { allowPending: true }),
  asyncHandler(verifyCurrentDriverRcDocument),
);
driverRouter.post(
  "/documents/:documentKey/verify-bank",
  authenticate(["driver"], { allowPending: true }),
  asyncHandler(verifyCurrentDriverBankDocument),
);
driverRouter.get(
  "/notifications",
  authenticate(["driver", "owner"]),
  asyncHandler(getDriverNotifications),
);
driverRouter.delete(
  "/notifications/:id",
  authenticate(["driver", "owner"]),
  asyncHandler(deleteDriverNotification),
);
driverRouter.delete(
  "/notifications",
  authenticate(["driver", "owner"]),
  asyncHandler(clearAllDriverNotifications),
);
driverRouter.delete(
  "/vehicle/:vehicleId",
  authenticate(["driver"]),
  asyncHandler(deleteDriverPrimaryVehicle),
);
driverRouter.get(
  "/scheduled-rides",
  authenticate(["driver"]),
  asyncHandler(getDriverScheduledRides),
);
driverRouter.post(
  "/scheduled-rides/:rideId/cancel",
  authenticate(["driver"]),
  asyncHandler(cancelDriverScheduledRide),
);
driverRouter.post(
  "/fcm-token",
  authenticate(["driver", "owner", "pooling_driver", "bus_driver"], { allowPending: true }),
  asyncHandler(saveDriverFcmToken),
);
driverRouter.get(
  "/wallet",
  authenticate(["driver"]),
  asyncHandler(getMyWallet),
);
driverRouter.get(
  "/incentives",
  authenticate(["driver"]),
  asyncHandler(getDriverIncentives),
);
driverRouter.post(
  "/incentives/claim",
  authenticate(["driver"]),
  asyncHandler(claimDriverIncentiveReward),
);
driverRouter.post(
  "/wallet/top-up/razorpay/callback",
  asyncHandler(handleDriverRazorpayWalletTopupCallback),
);
driverRouter.get(
  "/wallet/top-up/razorpay/callback",
  asyncHandler(handleDriverRazorpayWalletTopupCallback),
);
driverRouter.post(
    "/wallet/top-up/razorpay/order",
    authenticate(["driver"]),
    paymentOrderRateLimit,
    asyncHandler(createDriverWalletTopupOrder),
);
driverRouter.post(
    "/wallet/top-up/phonepe/order",
    authenticate(["driver"]),
    paymentOrderRateLimit,
    asyncHandler(createDriverPhonePeWalletTopupOrder),
);
  driverRouter.post(
    "/wallet/top-up/razorpay/verify",
    authenticate(["driver"]),
    asyncHandler(verifyDriverWalletTopup),
  );
  driverRouter.get(
    "/wallet/top-up/phonepe/status/:merchantTransactionId",
    authenticate(["driver"]),
    asyncHandler(verifyDriverPhonePeWalletTopup),
  );
driverRouter.post(
  "/wallet/withdrawals",
  authenticate(["driver"]),
  asyncHandler(createDriverWithdrawalRequest),
);

driverRouter.post(
  "/payments/qr",
  authenticate(["driver"]),
  asyncHandler(createDriverPaymentQr),
);
driverRouter.get(
  "/payments/qr/status",
  authenticate(["driver"]),
  asyncHandler(getDriverPaymentQrStatus),
);
driverRouter.patch(
  "/vehicle",
  authenticate(["driver"]),
  asyncHandler(updateDriverVehicle),
);
driverRouter.get("/approval-status", asyncHandler(getDriverApprovalStatus));
driverRouter.get(
  "/fleet/dashboard",
  authenticate(["owner"]),
  asyncHandler(getOwnerFleetDashboard),
);
driverRouter.get(
  "/fleet/bus-services",
  authenticate(["owner"]),
  asyncHandler(listOwnerBusServices),
);
driverRouter.get(
  "/fleet/bus-bookings",
  authenticate(["owner"]),
  asyncHandler(getOwnerBusBookings),
);
driverRouter.get(
  "/fleet/bus-bookings/calendar",
  authenticate(["owner"]),
  asyncHandler(getOwnerBusBookingCalendar),
);
driverRouter.post(
  "/fleet/bus-services",
  authenticate(["owner"]),
  asyncHandler(createOwnerBusService),
);
driverRouter.patch(
  "/fleet/bus-services/:id",
  authenticate(["owner"]),
  asyncHandler(updateOwnerBusService),
);
driverRouter.delete(
  "/fleet/bus-services/:id",
  authenticate(["owner"]),
  asyncHandler(deleteOwnerBusService),
);
driverRouter.post(
  "/fleet/bus-bookings/:id/cancel",
  authenticate(["owner"]),
  asyncHandler(cancelOwnerBusBookingSeats),
);
driverRouter.get(
  "/fleet/drivers",
  authenticate(["driver", "owner"]),
  asyncHandler(getOwnerFleetDrivers),
);
driverRouter.get(
  "/fleet/wallet",
  authenticate(["owner"]),
  asyncHandler(getOwnerFleetWallet),
);
driverRouter.get(
  "/fleet/zones",
  authenticate(["driver", "owner"]),
  asyncHandler(getOwnerFleetZones),
);
driverRouter.post(
  "/fleet/drivers",
  authenticate(["driver", "owner"]),
  asyncHandler(createOwnerFleetDriver),
);
driverRouter.patch(
  "/fleet/drivers/:driverId",
  authenticate(["driver", "owner"]),
  asyncHandler(updateOwnerFleetDriver),
);
driverRouter.get(
  "/fleet/vehicles",
  authenticate(["driver", "owner"]),
  asyncHandler(getOwnerFleetVehicles),
);
driverRouter.post(
  "/fleet/vehicles",
  authenticate(["driver", "owner"]),
  asyncHandler(addOwnerVehicle),
);
driverRouter.patch(
  "/fleet/vehicles/:vehicleId",
  authenticate(["driver", "owner"]),
  asyncHandler(updateOwnerFleetVehicle),
);
driverRouter.delete(
  "/fleet/vehicles/:vehicleId",
  authenticate(["driver", "owner"]),
  asyncHandler(deleteOwnerFleetVehicle),
);
driverRouter.get(
  "/fleet/pooling-vehicles",
  authenticate(["owner"]),
  asyncHandler(getOwnerPoolingVehicles),
);
driverRouter.post(
  "/fleet/pooling-vehicles",
  authenticate(["owner"]),
  asyncHandler(createOwnerPoolingVehicle),
);
driverRouter.patch(
  "/fleet/pooling-vehicles/:vehicleId",
  authenticate(["owner"]),
  asyncHandler(updateOwnerPoolingVehicle),
);
driverRouter.delete(
  "/fleet/pooling-vehicles/:vehicleId",
  authenticate(["owner"]),
  asyncHandler(deleteOwnerPoolingVehicle),
);
driverRouter.get("/service-locations", asyncHandler(getServiceLocations));
driverRouter.get(
  "/document-templates",
  asyncHandler(getDriverDocumentTemplates),
);
driverRouter.get(
  "/vehicle-field-templates",
  asyncHandler(getDriverVehicleFieldTemplates),
);
driverRouter.post("/onboarding/send-otp", asyncHandler(startOnboarding));
driverRouter.post("/onboarding/verify-otp", asyncHandler(verifyOnboardingOtp));
driverRouter.patch("/onboarding/role", asyncHandler(saveOnboardingRole));
driverRouter.get("/onboarding/signup-options", asyncHandler(getOnboardingSignupOptions));
driverRouter.patch("/onboarding/role-details", asyncHandler(saveOnboardingRoleDetails));
driverRouter.patch(
  "/onboarding/personal",
  asyncHandler(saveOnboardingPersonal),
);
driverRouter.patch(
  "/onboarding/referral",
  asyncHandler(saveOnboardingReferral),
);
driverRouter.patch("/onboarding/vehicle", asyncHandler(saveOnboardingVehicle));
driverRouter.post("/onboarding/vehicle/verify-rc", asyncHandler(verifyOnboardingVehicleRc));
driverRouter.post(
  "/onboarding/documents/:documentKey/verify-license",
  asyncHandler(verifyOnboardingLicenseDocument),
);
driverRouter.patch(
  "/onboarding/documents",
  asyncHandler(saveOnboardingDocuments),
);
driverRouter.post("/onboarding/complete", asyncHandler(completeOnboarding));
driverRouter.get(
  "/onboarding/session/:registrationId",
  asyncHandler(getOnboardingSession),
);
driverRouter.patch("/online", authenticate(["driver"]), asyncHandler(goOnline));
driverRouter.patch(
  "/offline",
  authenticate(["driver"]),
  asyncHandler(goOffline),
);
